#############################################################################
# Makefile for building: myfirstqt
# Generated by qmake (3.1) (Qt 6.11.2)
# Project:  myfirstqt.pro
# Template: app
# Command: /data/data/com.termux/files/usr/bin/qmake6 -o Makefile myfirstqt.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -fno-direct-access-external-data -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -fno-direct-access-external-data -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I../../usr/include/qt6 -I../../usr/include/qt6/QtWidgets -I../../usr/include/qt6/QtGui -I../../usr/include/qt6/QtCore -I. -I../../usr/lib/qt6/mkspecs/linux-clang
QMAKE         = /data/data/com.termux/files/usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /data/data/com.termux/files/usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /data/data/com.termux/files/usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = myfirstqt1.0.0
DISTDIR = /data/data/com.termux/files/home/myfirstqt/.tmp/myfirstqt1.0.0
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++ -Wl,-rpath,/data/data/com.termux/files/usr/lib -Wl,-rpath-link,/data/data/com.termux/files/usr/lib
LIBS          = $(SUBLIBS) /data/data/com.termux/files/usr/lib/libQt6Widgets.so /data/data/com.termux/files/usr/lib/libQt6Gui.so /data/data/com.termux/files/usr/lib/libGLX.so /data/data/com.termux/files/usr/lib/libOpenGL.so /data/data/com.termux/files/usr/lib/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = ../../usr/lib/qt6/mkspecs/features/spec_pre.prf \
		../../usr/lib/qt6/mkspecs/common/unix.conf \
		../../usr/lib/qt6/mkspecs/common/linux.conf \
		../../usr/lib/qt6/mkspecs/common/sanitize.conf \
		../../usr/lib/qt6/mkspecs/common/gcc-base.conf \
		../../usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		../../usr/lib/qt6/mkspecs/common/clang.conf \
		../../usr/lib/qt6/mkspecs/qconfig.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		../../usr/lib/qt6/mkspecs/features/qt_functions.prf \
		../../usr/lib/qt6/mkspecs/features/qt_config.prf \
		../../usr/lib/qt6/mkspecs/linux-clang/qmake.conf \
		../../usr/lib/qt6/mkspecs/features/spec_post.prf \
		../../usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		../../usr/lib/qt6/mkspecs/features/toolchain.prf \
		../../usr/lib/qt6/mkspecs/features/default_pre.prf \
		../../usr/lib/qt6/mkspecs/features/resolve_config.prf \
		../../usr/lib/qt6/mkspecs/features/default_post.prf \
		../../usr/lib/qt6/mkspecs/features/warn_on.prf \
		../../usr/lib/qt6/mkspecs/features/permissions.prf \
		../../usr/lib/qt6/mkspecs/features/qt.prf \
		../../usr/lib/qt6/mkspecs/features/resources_functions.prf \
		../../usr/lib/qt6/mkspecs/features/resources.prf \
		../../usr/lib/qt6/mkspecs/features/moc.prf \
		../../usr/lib/qt6/mkspecs/features/link_ltcg.prf \
		../../usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		../../usr/lib/qt6/mkspecs/features/uic.prf \
		../../usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf \
		../../usr/lib/qt6/mkspecs/features/unix/thread.prf \
		../../usr/lib/qt6/mkspecs/features/qmake_use.prf \
		../../usr/lib/qt6/mkspecs/features/file_copies.prf \
		../../usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		../../usr/lib/qt6/mkspecs/features/exceptions.prf \
		../../usr/lib/qt6/mkspecs/features/yacc.prf \
		../../usr/lib/qt6/mkspecs/features/lex.prf \
		myfirstqt.pro  main.cpp
QMAKE_TARGET  = myfirstqt
DESTDIR       = 
TARGET        = myfirstqt


first: all
####### Build rules

myfirstqt:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: myfirstqt.pro ../../usr/lib/qt6/mkspecs/linux-clang/qmake.conf ../../usr/lib/qt6/mkspecs/features/spec_pre.prf \
		../../usr/lib/qt6/mkspecs/common/unix.conf \
		../../usr/lib/qt6/mkspecs/common/linux.conf \
		../../usr/lib/qt6/mkspecs/common/sanitize.conf \
		../../usr/lib/qt6/mkspecs/common/gcc-base.conf \
		../../usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		../../usr/lib/qt6/mkspecs/common/clang.conf \
		../../usr/lib/qt6/mkspecs/qconfig.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		../../usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		../../usr/lib/qt6/mkspecs/features/qt_functions.prf \
		../../usr/lib/qt6/mkspecs/features/qt_config.prf \
		../../usr/lib/qt6/mkspecs/linux-clang/qmake.conf \
		../../usr/lib/qt6/mkspecs/features/spec_post.prf \
		../../usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		../../usr/lib/qt6/mkspecs/features/toolchain.prf \
		../../usr/lib/qt6/mkspecs/features/default_pre.prf \
		../../usr/lib/qt6/mkspecs/features/resolve_config.prf \
		../../usr/lib/qt6/mkspecs/features/default_post.prf \
		../../usr/lib/qt6/mkspecs/features/warn_on.prf \
		../../usr/lib/qt6/mkspecs/features/permissions.prf \
		../../usr/lib/qt6/mkspecs/features/qt.prf \
		../../usr/lib/qt6/mkspecs/features/resources_functions.prf \
		../../usr/lib/qt6/mkspecs/features/resources.prf \
		../../usr/lib/qt6/mkspecs/features/moc.prf \
		../../usr/lib/qt6/mkspecs/features/link_ltcg.prf \
		../../usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		../../usr/lib/qt6/mkspecs/features/uic.prf \
		../../usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf \
		../../usr/lib/qt6/mkspecs/features/unix/thread.prf \
		../../usr/lib/qt6/mkspecs/features/qmake_use.prf \
		../../usr/lib/qt6/mkspecs/features/file_copies.prf \
		../../usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		../../usr/lib/qt6/mkspecs/features/exceptions.prf \
		../../usr/lib/qt6/mkspecs/features/yacc.prf \
		../../usr/lib/qt6/mkspecs/features/lex.prf \
		myfirstqt.pro \
		../../usr/lib/libQt6Widgets.prl \
		../../usr/lib/libQt6Gui.prl \
		../../usr/lib/libQt6Core.prl
	$(QMAKE) -o Makefile myfirstqt.pro
../../usr/lib/qt6/mkspecs/features/spec_pre.prf:
../../usr/lib/qt6/mkspecs/common/unix.conf:
../../usr/lib/qt6/mkspecs/common/linux.conf:
../../usr/lib/qt6/mkspecs/common/sanitize.conf:
../../usr/lib/qt6/mkspecs/common/gcc-base.conf:
../../usr/lib/qt6/mkspecs/common/gcc-base-unix.conf:
../../usr/lib/qt6/mkspecs/common/clang.conf:
../../usr/lib/qt6/mkspecs/qconfig.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_core.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_network.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_testinternals_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri:
../../usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri:
../../usr/lib/qt6/mkspecs/features/qt_functions.prf:
../../usr/lib/qt6/mkspecs/features/qt_config.prf:
../../usr/lib/qt6/mkspecs/linux-clang/qmake.conf:
../../usr/lib/qt6/mkspecs/features/spec_post.prf:
../../usr/lib/qt6/mkspecs/features/exclusive_builds.prf:
../../usr/lib/qt6/mkspecs/features/toolchain.prf:
../../usr/lib/qt6/mkspecs/features/default_pre.prf:
../../usr/lib/qt6/mkspecs/features/resolve_config.prf:
../../usr/lib/qt6/mkspecs/features/default_post.prf:
../../usr/lib/qt6/mkspecs/features/warn_on.prf:
../../usr/lib/qt6/mkspecs/features/permissions.prf:
../../usr/lib/qt6/mkspecs/features/qt.prf:
../../usr/lib/qt6/mkspecs/features/resources_functions.prf:
../../usr/lib/qt6/mkspecs/features/resources.prf:
../../usr/lib/qt6/mkspecs/features/moc.prf:
../../usr/lib/qt6/mkspecs/features/link_ltcg.prf:
../../usr/lib/qt6/mkspecs/features/unix/opengl.prf:
../../usr/lib/qt6/mkspecs/features/uic.prf:
../../usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf:
../../usr/lib/qt6/mkspecs/features/unix/thread.prf:
../../usr/lib/qt6/mkspecs/features/qmake_use.prf:
../../usr/lib/qt6/mkspecs/features/file_copies.prf:
../../usr/lib/qt6/mkspecs/features/testcase_targets.prf:
../../usr/lib/qt6/mkspecs/features/exceptions.prf:
../../usr/lib/qt6/mkspecs/features/yacc.prf:
../../usr/lib/qt6/mkspecs/features/lex.prf:
myfirstqt.pro:
../../usr/lib/libQt6Widgets.prl:
../../usr/lib/libQt6Gui.prl:
../../usr/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile myfirstqt.pro

qmake_all: FORCE


all: Makefile myfirstqt

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../usr/lib/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../usr/lib/qt6/mkspecs/features/data/dummy.cpp
	clang++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h ../../usr/lib/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp ../../usr/include/qt6/QtWidgets/QApplication \
		../../usr/include/qt6/QtWidgets/qapplication.h \
		../../usr/include/qt6/QtWidgets/qtwidgetsglobal.h \
		../../usr/include/qt6/QtGui/qtguiglobal.h \
		../../usr/include/qt6/QtCore/qglobal.h \
		../../usr/include/qt6/QtCore/qtcoreglobal.h \
		../../usr/include/qt6/QtCore/qtversionchecks.h \
		../../usr/include/qt6/QtCore/qtconfiginclude.h \
		../../usr/include/qt6/QtCore/qconfig.h \
		../../usr/include/qt6/QtCore/qtcore-config.h \
		../../usr/include/qt6/QtCore/qtconfigmacros.h \
		../../usr/include/qt6/QtCore/qtdeprecationdefinitions.h \
		../../usr/include/qt6/QtCore/qcompilerdetection.h \
		../../usr/include/qt6/QtCore/qprocessordetection.h \
		../../usr/include/qt6/QtCore/qsystemdetection.h \
		../../usr/include/qt6/QtCore/qtcoreexports.h \
		../../usr/include/qt6/QtCore/qtdeprecationmarkers.h \
		../../usr/include/qt6/QtCore/qtclasshelpermacros.h \
		../../usr/include/qt6/QtCore/qtpreprocessorsupport.h \
		../../usr/include/qt6/QtCore/qassert.h \
		../../usr/include/qt6/QtCore/qtnoop.h \
		../../usr/include/qt6/QtCore/qtypes.h \
		../../usr/include/qt6/QtCore/qtversion.h \
		../../usr/include/qt6/QtCore/qtypeinfo.h \
		../../usr/include/qt6/QtCore/qcontainerfwd.h \
		../../usr/include/qt6/QtCore/qsysinfo.h \
		../../usr/include/qt6/QtCore/qlogging.h \
		../../usr/include/qt6/QtCore/qflags.h \
		../../usr/include/qt6/QtCore/qcompare_impl.h \
		../../usr/include/qt6/QtCore/qatomic.h \
		../../usr/include/qt6/QtCore/qbasicatomic.h \
		../../usr/include/qt6/QtCore/qatomic_cxx11.h \
		../../usr/include/qt6/QtCore/qgenericatomic.h \
		../../usr/include/qt6/QtCore/qyieldcpu.h \
		../../usr/include/qt6/QtCore/qconstructormacros.h \
		../../usr/include/qt6/QtCore/qdarwinhelpers.h \
		../../usr/include/qt6/QtCore/qexceptionhandling.h \
		../../usr/include/qt6/QtCore/qforeach.h \
		../../usr/include/qt6/QtCore/qttypetraits.h \
		../../usr/include/qt6/QtCore/qfunctionpointer.h \
		../../usr/include/qt6/QtCore/qglobalstatic.h \
		../../usr/include/qt6/QtCore/qmalloc.h \
		../../usr/include/qt6/QtCore/qminmax.h \
		../../usr/include/qt6/QtCore/qnumeric.h \
		../../usr/include/qt6/QtCore/q20type_traits.h \
		../../usr/include/qt6/QtCore/qoverload.h \
		../../usr/include/qt6/QtCore/qswap.h \
		../../usr/include/qt6/QtCore/qtenvironmentvariables.h \
		../../usr/include/qt6/QtCore/qtresource.h \
		../../usr/include/qt6/QtCore/qttranslation.h \
		../../usr/include/qt6/QtCore/qversiontagging.h \
		../../usr/include/qt6/QtGui/qtgui-config.h \
		../../usr/include/qt6/QtGui/qtguiexports.h \
		../../usr/include/qt6/QtWidgets/qtwidgets-config.h \
		../../usr/include/qt6/QtWidgets/qtwidgetsexports.h \
		../../usr/include/qt6/QtCore/qcoreapplication.h \
		../../usr/include/qt6/QtCore/qstring.h \
		../../usr/include/qt6/QtCore/qchar.h \
		../../usr/include/qt6/QtCore/qcompare.h \
		../../usr/include/qt6/QtCore/qstdlibdetection.h \
		../../usr/include/qt6/QtCore/qcomparehelpers.h \
		../../usr/include/qt6/QtCore/qstringview.h \
		../../usr/include/qt6/QtCore/qbytearray.h \
		../../usr/include/qt6/QtCore/qrefcount.h \
		../../usr/include/qt6/QtCore/qnamespace.h \
		../../usr/include/qt6/QtCore/qtmetamacros.h \
		../../usr/include/qt6/QtCore/qarraydata.h \
		../../usr/include/qt6/QtCore/qpair.h \
		../../usr/include/qt6/QtCore/qarraydatapointer.h \
		../../usr/include/qt6/QtCore/qarraydataops.h \
		../../usr/include/qt6/QtCore/qcontainertools_impl.h \
		../../usr/include/qt6/QtCore/qxptype_traits.h \
		../../usr/include/qt6/QtCore/q23type_traits.h \
		../../usr/include/qt6/QtCore/q20functional.h \
		../../usr/include/qt6/QtCore/q20memory.h \
		../../usr/include/qt6/QtCore/q17memory.h \
		../../usr/include/qt6/QtCore/qbytearrayalgorithms.h \
		../../usr/include/qt6/QtCore/qbytearrayview.h \
		../../usr/include/qt6/QtCore/qstringfwd.h \
		../../usr/include/qt6/QtCore/qstringalgorithms.h \
		../../usr/include/qt6/QtCore/qlatin1stringview.h \
		../../usr/include/qt6/QtCore/qanystringview.h \
		../../usr/include/qt6/QtCore/qutf8stringview.h \
		../../usr/include/qt6/QtCore/qstringtokenizer.h \
		../../usr/include/qt6/QtCore/qstringbuilder.h \
		../../usr/include/qt6/QtCore/qstringconverter.h \
		../../usr/include/qt6/QtCore/qstringconverter_base.h \
		../../usr/include/qt6/QtCore/qcoreevent.h \
		../../usr/include/qt6/QtCore/qbasictimer.h \
		../../usr/include/qt6/QtCore/qabstracteventdispatcher.h \
		../../usr/include/qt6/QtCore/qobject.h \
		../../usr/include/qt6/QtCore/qobjectdefs.h \
		../../usr/include/qt6/QtCore/qobjectdefs_impl.h \
		../../usr/include/qt6/QtCore/qfunctionaltools_impl.h \
		../../usr/include/qt6/QtCore/qlist.h \
		../../usr/include/qt6/QtCore/qhashfunctions.h \
		../../usr/include/qt6/QtCore/qiterator.h \
		../../usr/include/qt6/QtCore/qbytearraylist.h \
		../../usr/include/qt6/QtCore/qstringlist.h \
		../../usr/include/qt6/QtCore/qalgorithms.h \
		../../usr/include/qt6/QtCore/q20bit.h \
		../../usr/include/qt6/QtCore/qsimd.h \
		../../usr/include/qt6/QtCore/qstringmatcher.h \
		../../usr/include/qt6/QtCore/qscopedpointer.h \
		../../usr/include/qt6/QtCore/qmetatype.h \
		../../usr/include/qt6/QtCore/qdatastream.h \
		../../usr/include/qt6/QtCore/qiodevicebase.h \
		../../usr/include/qt6/QtCore/qfloat16.h \
		../../usr/include/qt6/QtCore/qmath.h \
		../../usr/include/qt6/QtCore/qtformat_impl.h \
		../../usr/include/qt6/QtCore/qiterable.h \
		../../usr/include/qt6/QtCore/qtaggedpointer.h \
		../../usr/include/qt6/QtCore/qmetacontainer.h \
		../../usr/include/qt6/QtCore/qcontainerinfo.h \
		../../usr/include/qt6/QtCore/qscopeguard.h \
		../../usr/include/qt6/QtCore/qobject_impl.h \
		../../usr/include/qt6/QtCore/qbindingstorage.h \
		../../usr/include/qt6/QtCore/qeventloop.h \
		../../usr/include/qt6/QtCore/qdeadlinetimer.h \
		../../usr/include/qt6/QtCore/qnativeinterface.h \
		../../usr/include/qt6/QtCore/qcoreapplication_platform.h \
		../../usr/include/qt6/QtCore/qfuture.h \
		../../usr/include/qt6/QtCore/qfutureinterface.h \
		../../usr/include/qt6/QtCore/qmutex.h \
		../../usr/include/qt6/QtCore/qtsan_impl.h \
		../../usr/include/qt6/QtCore/qresultstore.h \
		../../usr/include/qt6/QtCore/qmap.h \
		../../usr/include/qt6/QtCore/qshareddata.h \
		../../usr/include/qt6/QtCore/qshareddata_impl.h \
		../../usr/include/qt6/QtCore/qfuture_impl.h \
		../../usr/include/qt6/QtCore/qthreadpool.h \
		../../usr/include/qt6/QtCore/qthread.h \
		../../usr/include/qt6/QtCore/qrunnable.h \
		../../usr/include/qt6/QtCore/qexception.h \
		../../usr/include/qt6/QtCore/qpromise.h \
		../../usr/include/qt6/QtCore/qvariant.h \
		../../usr/include/qt6/QtCore/qdebug.h \
		../../usr/include/qt6/QtCore/qtextstream.h \
		../../usr/include/qt6/QtCore/qcontiguouscache.h \
		../../usr/include/qt6/QtCore/qsharedpointer.h \
		../../usr/include/qt6/QtCore/qsharedpointer_impl.h \
		../../usr/include/qt6/QtCore/qset.h \
		../../usr/include/qt6/QtCore/qhash.h \
		../../usr/include/qt6/QtCore/qvarlengtharray.h \
		../../usr/include/qt6/QtCore/qalloc.h \
		../../usr/include/qt6/QtCore/q23utility.h \
		../../usr/include/qt6/QtCore/q20utility.h \
		../../usr/include/qt6/QtGui/qwindowdefs.h \
		../../usr/include/qt6/QtCore/qpoint.h \
		../../usr/include/qt6/QtCore/qcheckedint_impl.h \
		../../usr/include/qt6/QtCore/qsize.h \
		../../usr/include/qt6/QtCore/qmargins.h \
		../../usr/include/qt6/QtGui/qcursor.h \
		../../usr/include/qt6/QtGui/qbitmap.h \
		../../usr/include/qt6/QtGui/qpixmap.h \
		../../usr/include/qt6/QtGui/qpaintdevice.h \
		../../usr/include/qt6/QtCore/qrect.h \
		../../usr/include/qt6/QtGui/qcolor.h \
		../../usr/include/qt6/QtGui/qrgb.h \
		../../usr/include/qt6/QtGui/qrgba64.h \
		../../usr/include/qt6/QtGui/qimage.h \
		../../usr/include/qt6/QtGui/qpixelformat.h \
		../../usr/include/qt6/QtGui/qtransform.h \
		../../usr/include/qt6/QtGui/qpolygon.h \
		../../usr/include/qt6/QtGui/qregion.h \
		../../usr/include/qt6/QtCore/qspan.h \
		../../usr/include/qt6/QtCore/q20iterator.h \
		../../usr/include/qt6/QtCore/qline.h \
		../../usr/include/qt6/QtGui/qguiapplication.h \
		../../usr/include/qt6/QtGui/qinputmethod.h \
		../../usr/include/qt6/QtCore/qlocale.h \
		../../usr/include/qt6/QtGui/qguiapplication_platform.h \
		../../usr/include/qt6/QtWidgets/QLabel \
		../../usr/include/qt6/QtWidgets/qlabel.h \
		../../usr/include/qt6/QtWidgets/qframe.h \
		../../usr/include/qt6/QtWidgets/qwidget.h \
		../../usr/include/qt6/QtGui/qaction.h \
		../../usr/include/qt6/QtGui/qkeysequence.h \
		../../usr/include/qt6/QtGui/qicon.h \
		../../usr/include/qt6/QtGui/qpalette.h \
		../../usr/include/qt6/QtGui/qbrush.h \
		../../usr/include/qt6/QtGui/qfont.h \
		../../usr/include/qt6/QtCore/qendian.h \
		../../usr/include/qt6/QtGui/qfontmetrics.h \
		../../usr/include/qt6/QtGui/qfontinfo.h \
		../../usr/include/qt6/QtGui/qfontvariableaxis.h \
		../../usr/include/qt6/QtWidgets/qsizepolicy.h \
		../../usr/include/qt6/QtGui/qevent.h \
		../../usr/include/qt6/QtCore/qiodevice.h \
		../../usr/include/qt6/QtCore/qurl.h \
		../../usr/include/qt6/QtGui/qeventpoint.h \
		../../usr/include/qt6/QtGui/qvector2d.h \
		../../usr/include/qt6/QtGui/qvectornd.h \
		../../usr/include/qt6/QtGui/qpointingdevice.h \
		../../usr/include/qt6/QtGui/qinputdevice.h \
		../../usr/include/qt6/QtGui/qscreen.h \
		../../usr/include/qt6/QtCore/QList \
		../../usr/include/qt6/QtCore/QObject \
		../../usr/include/qt6/QtCore/QRect \
		../../usr/include/qt6/QtCore/QSize \
		../../usr/include/qt6/QtCore/QSizeF \
		../../usr/include/qt6/QtGui/QTransform \
		../../usr/include/qt6/QtGui/qscreen_platform.h \
		../../usr/include/qt6/QtGui/qpicture.h \
		../../usr/include/qt6/QtGui/qtextdocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

